services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: seria_watchers
      MARIADB_USER: seria_watchers_user
      MARIADB_PASSWORD: seria_watchers_password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  database_data:
